/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyInVancouverRouteImport } from './routes/study-in-vancouver'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EnRouteImport } from './routes/en'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnStudyInVancouverRouteImport } from './routes/en.study-in-vancouver'
import { Route as EnServicesRouteImport } from './routes/en.services'
import { Route as EnCoursesRouteImport } from './routes/en.courses'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnConsultationRouteImport } from './routes/en.consultation'
import { Route as EnAboutRouteImport } from './routes/en.about'

const StudyInVancouverRoute = StudyInVancouverRouteImport.update({
  id: '/study-in-vancouver',
  path: '/study-in-vancouver',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnStudyInVancouverRoute = EnStudyInVancouverRouteImport.update({
  id: '/study-in-vancouver',
  path: '/study-in-vancouver',
  getParentRoute: () => EnRoute,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => EnRoute,
} as any)
const EnCoursesRoute = EnCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnConsultationRoute = EnConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/en': typeof EnRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-in-vancouver': typeof StudyInVancouverRoute
  '/en/about': typeof EnAboutRoute
  '/en/consultation': typeof EnConsultationRoute
  '/en/contact': typeof EnContactRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/services': typeof EnServicesRoute
  '/en/study-in-vancouver': typeof EnStudyInVancouverRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-in-vancouver': typeof StudyInVancouverRoute
  '/en/about': typeof EnAboutRoute
  '/en/consultation': typeof EnConsultationRoute
  '/en/contact': typeof EnContactRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/services': typeof EnServicesRoute
  '/en/study-in-vancouver': typeof EnStudyInVancouverRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/en': typeof EnRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-in-vancouver': typeof StudyInVancouverRoute
  '/en/about': typeof EnAboutRoute
  '/en/consultation': typeof EnConsultationRoute
  '/en/contact': typeof EnContactRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/services': typeof EnServicesRoute
  '/en/study-in-vancouver': typeof EnStudyInVancouverRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/courses'
    | '/en'
    | '/services'
    | '/sitemap.xml'
    | '/study-in-vancouver'
    | '/en/about'
    | '/en/consultation'
    | '/en/contact'
    | '/en/courses'
    | '/en/services'
    | '/en/study-in-vancouver'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/courses'
    | '/services'
    | '/sitemap.xml'
    | '/study-in-vancouver'
    | '/en/about'
    | '/en/consultation'
    | '/en/contact'
    | '/en/courses'
    | '/en/services'
    | '/en/study-in-vancouver'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/courses'
    | '/en'
    | '/services'
    | '/sitemap.xml'
    | '/study-in-vancouver'
    | '/en/about'
    | '/en/consultation'
    | '/en/contact'
    | '/en/courses'
    | '/en/services'
    | '/en/study-in-vancouver'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  EnRoute: typeof EnRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyInVancouverRoute: typeof StudyInVancouverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-in-vancouver': {
      id: '/study-in-vancouver'
      path: '/study-in-vancouver'
      fullPath: '/study-in-vancouver'
      preLoaderRoute: typeof StudyInVancouverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/study-in-vancouver': {
      id: '/en/study-in-vancouver'
      path: '/study-in-vancouver'
      fullPath: '/en/study-in-vancouver'
      preLoaderRoute: typeof EnStudyInVancouverRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/services': {
      id: '/en/services'
      path: '/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/courses': {
      id: '/en/courses'
      path: '/courses'
      fullPath: '/en/courses'
      preLoaderRoute: typeof EnCoursesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/consultation': {
      id: '/en/consultation'
      path: '/consultation'
      fullPath: '/en/consultation'
      preLoaderRoute: typeof EnConsultationRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnConsultationRoute: typeof EnConsultationRoute
  EnContactRoute: typeof EnContactRoute
  EnCoursesRoute: typeof EnCoursesRoute
  EnServicesRoute: typeof EnServicesRoute
  EnStudyInVancouverRoute: typeof EnStudyInVancouverRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnConsultationRoute: EnConsultationRoute,
  EnContactRoute: EnContactRoute,
  EnCoursesRoute: EnCoursesRoute,
  EnServicesRoute: EnServicesRoute,
  EnStudyInVancouverRoute: EnStudyInVancouverRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  EnRoute: EnRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyInVancouverRoute: StudyInVancouverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
